### ISSUE TITLE
feat: Add a common breadcrumbs component

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#101]
### What feature?

- [x] Add a common breadcrumbs component
- [x] On link hover, the color of the link should be changed to brand-hover, and the underline should appear
- [x] Current item shouldn't be a link

### Screenshots

![Image](https://github.com/user-attachments/assets/2dd2c81b-119c-42d9-9142-00dece6cd3e9)

**Comment by AnnaRomaniuta** [comment]
**User Story:** As a user, I want to navigate easily within the "Projects" section using a breadcrumbs component, so that I can keep track of my current location and move between different project levels efficiently.

**Acceptance Criteria:**
1. The user shall see a breadcrumbs trail at the top of the "Projects" section, indicating their current location within the project hierarchy (e.g., "Projects > Project Name").
2. The breadcrumb links should change color to the brand-hover color when hovered, and an underline should appear.
3. The current project name in the breadcrumb trail should be displayed as plain text and should not be a clickable link.

**Comment by Fjortis** [comment]
Apologies for the delayed response. I've made significant progress on the breadcrumbs component and have successfully implemented Acceptance Criteria 2 and 3:

Acceptance Criterion 2: The breadcrumb links now change to the brand-hover color and are underlined when hovered over.
Acceptance Criterion 3: The current project name is displayed as plain text and is not a clickable link, ensuring clarity on the user’s current location.
For Acceptance Criterion 1, which involves displaying the breadcrumbs trail to indicate the user's current location within the project hierarchy, this can be achieved by adjusting the breadcrumbs data according to the current page. Since / is the route for the "Projects" section, here’s how the breadcrumbs would be configured:

`<Breadcrumbs
  items={[
    { label: "Projects" }, // The current page, not clickable
  ]}
/>`

On a Specific Project Page (e.g., Projects > Project Name):
`<Breadcrumbs
  items={[
    { href: "/", label: "Projects" },
    { label: "Project Name" }, // The current page, not clickable
  ]}
/>`

**Comment by AnnaRomaniuta** [comment]
Everything works fine, thanks!
