### ISSUE TITLE
feat: Add an ability to delete a project

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#138]
### What feature?

- [x] Add delete option to the Projects table options menu.
- [x] When Delete is clicked a confirmation modal should be shown.
- [x] After confirmation, the project should be deleted and disappear from the list.

### Screenshots

![Image](https://github.com/user-attachments/assets/320758ac-9fef-4a1d-844e-f9834c4e0b52)

![Image](https://github.com/user-attachments/assets/e4b1c161-05cb-4a9a-8cb2-db26987cd536)

**Comment by AnnaRomaniuta** [comment]
**User Story:**
As a user, I want to delete a project from the "Projects" section, so that I can remove unnecessary projects from the list.

**Acceptance Criteria:**
1. The user shall see a "Delete" option in the "Options" menu next to each project.
2. When "Delete" is clicked, the user shall see a confirmation modal to confirm the action.
3. After confirmation, the current project is removed from the "Projects" list.

**Comment by VeronikaHordus** [comment]
Works great, all follows the requirements. Thank you!
