### ISSUE TITLE
feat: Add an ability to generate and retrieve project api key

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#180]
### What feature?

- [x] We need to add a new table that will store project_api_keys, it should contain encoded_key, project_id, and user_id columns. project_id - user_id pair should be unique.
- [x] Before we insert the key into the database, we need to encrypt it. And when we retrieve it (to send it to the client), we will need to decrypt it.
- [x] We need to attach this token in response when we get a project by id.
- [x] On the frontend we need to add the "Setup Analytics" button which will open a modal.
- [x] For now, the modal will only contain a field for displaying api token and "Generate" button.
- [x] When the token is present, "Generate" button should be disabled.

Notes: 

- We might be able to implement this using our current token service, but this is to be determined during implementation.
- An ability to re-generate API tokens will be added in future iterations.

### Screenshots

![Setup analytics modal](https://github.com/user-attachments/assets/aa9e208f-732c-497a-8880-48c16758350e)

**Comment by GvoFor** [comment]
>...an icon indicator showing loading and green tick is shown.

Can you specify, how indicator should look like (should it be green "broken" ring?), where this indicatior should be placed, and where green tick should be shown

**Comment by GvoFor** [comment]
@liza-veis
What should be the route for generation api key?
Should it be `.../api/v1/projects/{id}/api-key` or something else?

**Comment by liza-veis** [comment]
> What should be the route for generation api key?
> Should it be .../api/v1/projects/{id}/api-key or something else?

Let's use `/api/v1/project-api-keys` as a separate resource

**Comment by GvoFor** [comment]
Will we need to be able to retrieve all the keys (`findAll`) and retrieve by id (`getById`) for this resource?

I'm writing because I already add all the stuff needed for this (and this even already works), but now I realized, that for `"We need to attach this token in response when we get a project by id." ` I can just use some `findByProjectId` method from `projectApiKeysService` inside `projectService`, without any additional REST API, so I it seems to me, that I was supposed only to add `POST` method for api key creation for that route...

So should I delete `GET` methods responsible for retrieving all api keys, and api key by id?

Also want to clarify. I created separate module `project-api-keys` for this. Is it right?

**Comment by liza-veis** [comment]
> Will we need to be able to retrieve all the keys (findAll) and retrieve by id (getById) for this resource?

In the next two weeks, we are not planning to add something like this. We only will need to search by the encrypted_key field. So let's remove unused methods.

> it seems to me, that I was supposed only to add POST method for api key creation for that route

That's right, no additional routes are needed.

> Also want to clarify. I created separate module project-api-keys for this. Is it right?

yes, because it's a separate resource to work with

**Comment by GvoFor** [comment]
## UPDATE
We decided to change the flow:
- api key is bind to the project and not to the pair (project, user): so for each project there will be only one api key, and all the users will see this key
- `project_api_keys` should have such columns: `encrypted_key`, `project_id`, `created_by`, `updated_by` (as well as `id`, `created_at`, `updated_at`). `project_id` should be unique

**Comment by AnnaRomaniuta** [comment]
Good job! Thanks!
