### ISSUE TITLE
feat: Add date input to analytics page

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#182]
### What feature?

- [ ] Create a common date input component. https://www.npmjs.com/package/react-calendar
- [ ] The design should be similar to the Figma design but may differ significantly depending on which customization the library provides.
- [ ] Add an analytics page and place the input there.
- [x] On the analytics page, the user should be able to select only past dates and no more than 1 month period.

### Screenshots

![Image](https://github.com/user-attachments/assets/8d973c88-7124-4b96-9e0c-6fc0694bf979)

![Image](https://github.com/user-attachments/assets/af647eb4-9120-4c4c-a533-9d77c3a73f20)

**Comment by VeronikaHordus** [comment]
User Story:
As a manager, I want to select a specific month to view analytics, so that I can easily assess and analyze the progress and trends within that exact period of time.

Acceptance Criteria: 
1. Users can select a specific month from a dropdown menu or calendar component, rather than manually inputting a custom date range.
2. Once a month is selected, the chosen time range should be clearly highlighted or displayed on the date input field.
3. The default selection should equal the current month.

**Comment by Vitaliistf** [comment]
@liza-veis @VeronikaHordus Just to clarify. 
1. As I understand, the datepicker on the second image is a pop-up (pop-over)?
2. Also, could you please explain more detailed about dropdown menu? Should it be something like select? And, as I understand we won't put the every month of every year of human history in there 😅, so how should it be limited? Last 12 months, or all months from the start of the year till now?

**Comment by VeronikaHordus** [comment]
Sorry, My bad with dropdown menu - I ment the pop-up of the datepicker.
About the time limits we will wait for Liza.

**Comment by liza-veis** [comment]
> Also, could you please explain more about dropdown menu? Should it be something like select? And, as I understand we won't put the every month of every year of human history in there 😅, so how should it be limited? Last 12 months, or all months from the start of the year till now?

all the years available by the library is fine for now 😅

**Comment by VeronikaHordus** [comment]
Looks good!
