### ISSUE TITLE
feat: Save search value to query parameters

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#200]
### What feature?

- [x] When searching for projects we need to save search value to query parameters.
- [x] After reloading the page, we should take the initial state from query params and filter the projects accordingly.
- [x]  adjust GET all projects request for cases where name is missing

**Comment by AnnaRomaniuta** [comment]
**User Story:**
As a user, I want the search value to be saved in the query parameters when searching for projects, so that when I reload the page, the search state is preserved, and the projects are filtered accordingly.

**Acceptance Criteria:**
1. The search value is saved to the query parameters when a user searches for projects.
2. Upon reloading the page, the initial state of the search is taken from the query parameters and applied to filter the projects.
3. The page behaves consistently across reloads, preserving the user's search query.

**Comment by AnnaRomaniuta** [comment]
Everything works great. Good job!
