### ISSUE TITLE
feat: Add admin group

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#227]
### What feature?

- [x] Add "Admins" group to the database through migration
- [x] Add "manage_user_access" permission to this group

**Comment by AnnaRomaniuta** [comment]
**User Story:**
As an administrator, I want to have an "Admins" group with specific permissions, so that users assigned to this group can manage user access within the application. 

**Acceptance Criteria:**
1. A new "Admins" group is added to the database via a migration.
2. The "manage_user_access" permission is assigned to the "Admins" group.
3. Users within the "Admins" group are able to view and manage user access permissions.

**Comment by AnnaRomaniuta** [comment]
Good job! Thanks!
