### ISSUE TITLE
feat: Create a table pagination component

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#23]
### What feature?

- [x] Create a common table pagination component
- [x] `page` and `perPage` parameters should be stored as URL query string
- [x] "Rows per page" select should contain such options: 10, 25, 50 (Select will be implement here #24)

### Screenshots

![Pagination](https://github.com/user-attachments/assets/1ae61526-93ac-40c0-9757-7ecebce94e51)

**Comment by GvoFor** [comment]
![image](https://github.com/user-attachments/assets/ee790e71-c5fa-4441-baf1-ac3132b41889)
Should this part be rendered if there is `1 of 1 pages`?

And what about edge cases: do I need to disable buttons (so user can't press them and cursor do not change), which cannot change table (i.e. If there is 10 pages, and current on is first, then first two buttons (`go to start` and `go to previous`) are make no sence, cause there is nowhere to move). Or maybe those button even must disapper, instead of become disabled?

Also according to the design, I see that the background color of those buttons is transperent. Do I need to change it on hover (with configured transition?). If so, then what color should it changed to? (one of the figma, or transpepent black, so it looks like tint)

**Comment by GvoFor** [comment]
> `page` and `perPage` parameters should be stored as URL query string
This means that I don't need any state inside my component, and can just get handlers for buttons/select throuh the props, right?

**Comment by liza-veis** [comment]
> Should this part be rendered if there is 1 of 1 pages?

yes

> And what about edge cases: do I need to disable buttons (so user can't press them and cursor do not change), which cannot change table (i.e. If there is 10 pages, and current on is first, then first two buttons (go to start and go to previous) are make no sence, cause there is nowhere to move). Or maybe those button even must disapper, instead of become disabled?

let's disable buttons, if there are no pages left to move. 

> page and perPage parameters should be stored as URL query string
> > This means that I don't need any state inside my component, and can just get handlers for buttons/select throuh the props, right?

I think there should be a custom hook, like usePagination. Perhaps, you will need both the state inside it and query parameters. You will need to take initial data from query params, then you may need to store parsed info in the local state, and whenever something changes, update query params.

**Comment by VeronikaHordus** [comment]
Everything is good, thank you !
