### ISSUE TITLE
feat: Add permission to view all projects

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#230]
### What feature?

- [x] Add view_all_projects permission (name: "View All Projects") to the permissions table.
- [x] Only users with this permission should be able to see projects item in the sidebar and access `GET /projects` and `GET /projects/:id` routes.

**Comment by AnnaRomaniuta** [comment]
**User Story:** 
As a user with restricted permissions, I want to have a "View All Projects" permission, so that I can access the list of projects and view specific project details without the ability to modify them.

**Acceptance Criteria:**
1. Add "View All Projects" permission (name: view_all_projects) to the permissions table.
2. Users with this permission can see the "Projects" item in the sidebar.
3. Users can access the GET /projects and GET /projects/:id routes.
4. Users without this permission cannot see the "Projects" item or access the routes mentioned.

**Comment by AnnaRomaniuta** [comment]
@sandrvvu Thanks for the clarification. I didn't write the last point correctly. I understand that users with limited access can see "Projects", "Analytics" and "Contributors".

**Comment by liza-veis** [comment]
> @liza-veis @AnnaRomaniuta What should see users without permission after entering to the system (earlier we redirected users to the projects page)?

That's a good question. First let's change the route for projects to `/projects`. Then I would say that logically we always need to redirect to the first available item in the sidebar. And in case there are no items, redirect to the `/` page which will be empty for now (we will add placeholder later). Would it be easy to implement ? I mean redirection to the first available item in the sidebar, when we enter the app

**Comment by liza-veis** [comment]
> @sandrvvu Thanks for the clarification. I didn't write the last point correctly. I understand that users with limited access can see "Projects", "Analytics" and "Contributors". 
@AnnaRomaniuta you were right in the initial requirement, we will hide unavailable items from the sidebar.

**Comment by VeronikaHordus** [comment]
Everuthing look good!
