### ISSUE TITLE
feat: Add permission to manage all projects

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#248]
### What feature?

- [x] Add manage_all_projects permission (name: "Manage All Projects") to the permissions table.
- [x] Users with this permission should be able to see projects item in the sidebar and view, create, edit (including project groups), and delete projects.

**Comment by VeronikaHordus** [comment]
User Story:
As a manager with lots of users I want to grant users with "Manage All Projects" permission, so that they can access the list of projects and view specific project details with an ability to modify them.

Acceptance Criteria:

Users with this permission can see the "Projects" item in the sidebar.
Users can access the GET /projects and GET /projects/:id routes.
The options button is visible for such users on the Specific project page.
User have an access to the Access Managment though the Options button on the Specific project page.
User can edit, delete projects as well as view Access Managment page of the certain project.
