### ISSUE TITLE
feat: Add an ability to search users when creating a group

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#270]
### What feature?

- [x] Add search input for users table to create / edit group modal.

### Screenshots

![Create group modal](https://github.com/user-attachments/assets/c130368c-79e7-4d87-851f-d7a6787b85ce)

**Comment by VeronikaHordus** [comment]
User Story: 
As a manager with a lot of items in my Users table, I want have a search option in the Create/Edit group modal, so that I can easily find the needed users and rise the efficiency of the time used for managing users group.

Access criteria:
1. The "No users matching your search criteria" is shown in the Users table when no matched results are found.
2. The search filed location and design should be consistent to the mockup.

**Comment by AnnaRomaniuta** [comment]
Trivial bugs were found, but the search field works well. Good job!
