### ISSUE TITLE
feat: Add an ability to merge contributors

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#344]
### What feature?

- [x] Add an option to merge contributors on Contributors page.
- [x] Add the same option to the contributor items on the project details page.
- [x] After the option is clicked, a modal should be opened.
- [x] The modal should display the current contributor with email and select with ability select another contributor.
- [x] After submission, selected contributor git emails should be transferred the current contributor and the selected contributor is deleted then.

### Screenshots

![Screenshot 2024-09-16 at 22 06 57](https://github.com/user-attachments/assets/8aef6079-ba49-4904-a767-45276d8a6e2f)
![Merge Contributors](https://github.com/user-attachments/assets/33b0e42d-c71e-41f0-b54b-0d85f5197708)

**Comment by VeronikaHordus** [comment]
**User Story :**

As a Project manager, I want to be able to merge contributors , so that I can consolidate contributor data and ensure all relevant information, such as Git emails, is associated with a single contributor.

Acceptance criteria: 

- A "Merge Contributor" option is available on the Contributors page for each contributor. The same "Merge Contributor" option is also available on contributor items in the Specific Project  page.
- The "Curent Contributor" dropdown in the modal must list all available contributors to choose from for merging.
- On the select "Contributor to merge with" dropdown list the user can only select a contributor who is not the current contributor to avoid self-merging. All contributors are listed.
- After the merge, the current contributor should display the combined Git emails from both contributors.

**Comment by VeronikaHordus** [comment]
Nicely done 💯
