### ISSUE TITLE
feat: Add an ability to edit contributor name

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#345]
### What feature?

- [x] Add edit option to contributors page.
- [x] Add the same option to contributor items on project details page.
- [x] When clicked, the modal should be opened. The modal should display Name, Git Emails and Projects fields. Only Name is editable.
- [x] User should be able to update contributor name.

### Screenshots

![Screenshot 2024-09-16 at 22 06 57](https://github.com/user-attachments/assets/2b45435b-373b-4c5d-8d8a-765981a0c05d)
![Update Contributor](https://github.com/user-attachments/assets/283b2998-1c55-416c-ac9f-eb40286f6cd7)

**Comment by VeronikaHordus** [comment]
User story: 
As a user, I want to edit a contributor’s name on the Contributors page and Project Details page, so that I can keep contributor information up to date and accurate.

Acceptance Criteria: 

- The "Update Contributor" modal opens pre-populated.
- After submitting the form, the information displayed updated on the page.
- The contributor Name field in the modal have the same validation rules as for User Name (from 1 to 50 characters, can consist of alphanumeric characters, cannot be empthy)

**Comment by AnnaRomaniuta** [comment]
Works well! Good job!
