### ISSUE TITLE
feat: Add projects select to analytics page

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#348]
### What feature?

- [x] When the project is selected only contributors from this project should be shown.

### Screenshots

![Screenshot 2024-09-16 at 22 26 16](https://github.com/user-attachments/assets/87963ce8-396d-45c4-9eff-8c5083c54e6e)

**Comment by VeronikaHordus** [comment]
**User Story :**
As a Manager leading several projects, I want to be able to select a specific project on the analytics page, so that I can focus on the progress and activity of the contributors related to that particular project.

Acceptance Criteria: 

- A dropdown list or selection is available on the analytics page, allowing the manager to choose a specific project from a list of all availible projects.
- Once a project is selected, only contributors from the selected project are displayed in the list.
- The Selected project name should be displayed in the Select component

**Comment by AnnaRomaniuta** [comment]
Found a trivial bug, created a bug report. In general, everything works well.
