### ISSUE TITLE
feat: Redirect to analytics page on contributor item click

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#349]
### What feature?

- [x] When a user clicks on a contributor item on the project details page, he should be navigated to analytics page with the project preselected.

Project select is added here #470

**Comment by VeronikaHordus** [comment]
**User Story:**
As a Manager, I want to be navigated to the analytics page with the project preselected when I click on a contributor item on the project details page, so that I can easily view relevant analytics for that specific project without needing to manually select it.

Acceptance Criteria: 

- The project associated with the contributor is preselected on the analytics page.
- The analytics page should load with all relevant data for the preselected project.
- The time range on the Analytics page should show the information of last month.
- If the Analytics page have an error while loading analytics data - the propper Error Toast notification should be shown

**Comment by AnnaRomaniuta** [comment]
Everything works fine. Only it is impossible to return to the project page through the browser arrow, for this I created a bug report.
