### ISSUE TITLE
feat: Add search field to analytics page

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#352]
### What feature?

- [ ] Add an ability to search by contributor name to analytics page.

### Screenshots

![Screenshot 2024-09-16 at 22 26 16](https://github.com/user-attachments/assets/87963ce8-396d-45c4-9eff-8c5083c54e6e)

**Comment by AnnaRomaniuta** [comment]
**User Story:** 
As a user, I want to search for contributors by name on the "Analytics" page, so that I can quickly locate specific contributors and view their activity data efficiently.

**Acceptance Criteria:**

1. A "Search" field should be available at the top of the "Analytics" page.
2. The user should be able to input a contributor's name into the search field.
3. As the user types, the list of contributors should filter to display only the matching names.
4. If no contributors match the search input, a "No users matching your search criteria." 
5. The search should be case-insensitive and allow partial matches (e.g., typing "Ann" should return both "Ann Smith" and "Anna Johnson").
6. The contributor list should update in real-time as the user types into the search field.
7. Clearing the search input should reset the contributor list to show all contributors.

**Comment by VeronikaHordus** [comment]
Looks good, there was 1 bug and it's already in ToDo for you)
