### ISSUE TITLE
feat: Replace forever with pm2 for analytics script

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#385]
### What feature?

- [x] Replace forever with pm2 for analytics script.

Please check that the script is restarted automatically after reboot. This can be implemented with feature below:

https://pm2.keymetrics.io/docs/usage/startup/

**Comment by s1rserg** [comment]
@liza-veis, I was able to get the previous functionality working with pm2. It took a bit longer than expected as I encountered some issues trying to run it with tsx, particularly issues with interpreters. However, everything works fine in the build. 
Currently, I'm looking into pm2’s 'restart on reboot' feature. According to the documentation, this feature is only suitable for Unix systems, and for Windows, there seems to be a separate module with its own installation process. Do I need to create this functionality for both types of systems?

**Comment by liza-veis** [comment]
Let's set up for unix only for now

**Comment by s1rserg** [comment]
I've done some research on how we can implement this feature. The user will need to have PM2 installed globally, and then they will need to run two commands.

The first command will return a config string that needs to be executed in the terminal. It looks like this:
```
$ pm2 startup
[PM2] You have to run this command as root. Execute the following command:
      sudo su -c "env PATH=$PATH:/home/unitech/.nvm/versions/node/v14.3/bin pm2 startup <distribution> -u <user> --hp <home-path>
```
The challenge here is that this config string needs to be populated with values specific to the user's environment. While I could use my executeCommand helper to run the command and log the output to a file, it seems like it might be more convenient for the user to simply run the command themselves instead of searching through log files.

The second command is straightforward and can be executed once the process is running, so no issues there.

**Comment by liza-veis** [comment]
> The challenge here is that this config string needs to be populated with values specific to the user's environment. While I could use my executeCommand helper to run the command and log the output to a file, it seems like it might be more convenient for the user to simply run the command themselves instead of searching through log files.

Sounds ok to me if this command is run by user, agree that it will be more convenient. We also will need to update script instructions then. FYI there is currently an issue with workspaces on published script, so don't try to run it by the command displayed in the instruction, but it will be available soon 😅.

**Comment by VeronikaHordus** [comment]
Looks like all right
