### ISSUE TITLE
fix:  Incorrect input size on Analytics Page

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#507]
### Describe your issue

The "Select Project" input field on the Analytics page displays an incorrect font size. The current font size is 14px, but according to the design specifications, it should be 16px.

### Steps to reproduce

1. Navigate to the Analytics page.
2. Locate the "Select Project" input field.
3. Inspect the font size of the input.

### What was the actual result?

The font size of the "Select Project" input field is set to 14px.

### What was the expected result?

The font size of the "Select Project" input field should be 16px.
![Image](https://github.com/user-attachments/assets/465ac1f1-4475-40ca-b7eb-b92e233b431b)

### Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/4c88f09b-7a90-4456-a81b-3379939138e5)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Trivial (S5)

**Comment by AnnaRomaniuta** [comment]
I still want to clarify about the color, everything looks good, but in Devtools I see what it is text-primary.  Maybe I'm confused and I'm not looking there. The text color for the input field is expected to be text-secondary.
![Image](https://github.com/user-attachments/assets/bb5c7623-331f-4dca-94e9-06e4a19a6259)

**Comment by AnutkaGn** [comment]
I looked at the code, and according to the styles, everything is fine. There is no problem with font size, because you have watched it on body styles, but for text in this component font-size is 16px.

Styles for the placeholder in the input (when the project is not yet selected)
![image](https://github.com/user-attachments/assets/a9ead518-dbb2-4113-a2fe-1a67c38acd8b)

Styles for the text of the project in the input (when the project is selected)
![image](https://github.com/user-attachments/assets/a5ad28f3-4267-4f6e-9ea0-1ec0777212e9)

**Comment by AnnaRomaniuta** [comment]
I checked locally and everything is fine. I cannot understand why these elements are called differently in the environment and locally.
![Image](https://github.com/user-attachments/assets/ea30173d-7604-422c-b852-2cd348c9d3d4)
