### ISSUE TITLE
feat: Add an ability to delete a group

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#80]
### What feature?

- [x] Add an options icon at the end of the Groups table row.
- [x] On the icon click an options menu should be opened with a delete option.
- [x] When Delete is clicked a confirmation modal should be shown.
- [x] After confirmation, the group should be deleted and disappear from the list.

### Screenshots

![Image](https://github.com/user-attachments/assets/320758ac-9fef-4a1d-844e-f9834c4e0b52)

![Image](https://github.com/user-attachments/assets/5beec1d4-3148-47ef-83ef-7307c4962d11)

**Comment by AnnaRomaniuta** [comment]
**User Story:** As a user, I want to be able to delete a group directly from the Groups table, so that I can easily manage and remove groups that are no longer needed.

**Acceptance Criteria:**
1. The user shall see an options icon at the end of each group row, which opens a menu with "Edit" and "Delete" options when clicked.
2. Clicking "Delete" shall open a confirmation modal asking the user to confirm the group deletion.
3. Confirming the deletion shall remove the group from the Groups table.

**Comment by VeronikaHordus** [comment]
Seems to be perfect, thank you!
