### ISSUE TITLE
feat: Add an ability to edit a group

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#81]
### What feature?

- [ ] Add an edit item to the options menu on the Groups table row.
- [ ] When Edit is clicked, a modal should be opened to edit the group.
- [ ] The modal and the validation are the same as for group creation (#79) except for two things:
  - [ ] The title should be "Update group".
  - [ ] The modal should be prepopulated with the current data for the group.
  - [ ] The label for the submit button should be "Update".

### Screenshots

![Image](https://github.com/user-attachments/assets/8878f32d-b2e8-4eb3-bd76-ece5f3ad8446)
![Image](https://github.com/user-attachments/assets/60b85f5a-c123-42c2-ab3a-d4fd096dc668)

**Comment by VeronikaHordus** [comment]
**User Story:** 
As a manager with multiple projects and team members in a rapidly growing environment, 
I want to edit, and manage user groups directly from the Access Management page,
So that I can efficiently update specific group participants and modify their permissions based on project requirements and evolving company needs.

**Acceptance Criteria:**

- The current group details (such as name, users, permissions) should be displayed in the edit modal pre-populated with the current group data.
- Users should be able to save changes after editing the group details by clicking the “Update” button, and the updated information should be immediately reflected in the groups list.
- Users must be able to close the modal with a click on a cross in the top right corner.
- After a successful update a toast notification indicating that the group has been updated must be shown.

**Comment by VeronikaHordus** [comment]
Works as required as for me. Thank you!
