### ISSUE TITLE
feat: Add pagination to the groups table

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#83]
### What feature?

- [x] Add pagination to the groups table on the access management page.

The groups table is added here #78

### Screenshots

![Image](https://github.com/user-attachments/assets/937602cf-ea85-4eef-a84d-2fbe51b8924d)

**Comment by VeronikaHordus** [comment]
**User Story:**
As a user,
I want to have pagination controls displayed directly under the data table,
So that I can easily navigate through multiple pages of data without needing to scroll or search for pagination controls

**Acceptance Criteria:**
- Pagination controls ("First", "Previous," "Next,", "Last", page numbers, etc.) should be positioned directly under the table.

**Comment by AnnaRomaniuta** [comment]
Everything works fine, thanks!
