### ISSUE TITLE
feat: Add an ability to edit a project

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#88]
### What feature?

- [x] Add an options icon at the end of the project list item.
- [x] When the icon is clicked, an options menu should be opened with an Edit option.
- [x] On the Edit item click, a modal should be opened to update a project.
- [x] The data for the modal should be prepopulated with the current project data.
- [x] The validation is the same as for project creation #57

### Screenshots

![Image](https://github.com/user-attachments/assets/0ebdb044-1498-4948-ad50-eb4f6bed44f3)
![Image](https://github.com/user-attachments/assets/541868a4-0665-455a-94fe-dec5265ce1bb)

**Comment by AnnaRomaniuta** [comment]
**User Story:**
As a user, I want to be able to edit a project's details directly from the project list, so that I can easily make updates without navigating away from the list.
**Acceptance Criteria:**
1. User shall be able to access the project editing option from the project list by clicking the options icon at the end of a project list item.
2. The current project details (name, description, etc.) are displayed in the edit modal pre-populated with the existing project data.
3. The edit modal shall have input fields with the same validation rules as the project creation form.
4. User shall be able to save changes after editing the project details, and the updated information should be immediately reflected in the project list.
5. Upon successful update, a confirmation message indicating that the project has been successfully updated is displayed to the user.

**Comment by VeronikaHordus** [comment]
It works good, Thank you !
Made 1 small bug though
